apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databaseinstances.paldab.io
spec:
  group: paldab.io
  names:
    kind: DatabaseInstance
    listKind: DatabaseInstanceList
    plural: databaseinstances
    singular: databaseinstance
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - type
                - statefulSetRef
              properties:
                type:
                  type: string
                  enum:
                    - mysql
                    - postgres
                    - mongodb
                statefulSetRef:
                  type: object
                  required:
                    - name
                    - namespace
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                scaleOnPodPresence:
                  type: boolean
            status:
              type: object
              properties:
                healthy:
                  type: boolean
                lastChecked:
                  type: string
                message:
                  type: string

