name: Sonarqube scan

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  sonarqube-scan:
    name: Sonarqube quality scan
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

